### DISCUSSION TITLE
How can a Noobaa Account / OBC have write-access to multiple Buckets in v5.13.0

### DISCUSSION THREAD

**Discussion by schwienbier** [noobaa/noobaa-operator#1173] [Q&A]
Dear Noobaa Supports,

we are using Noobaa v5.13.0 on k8s v1.25. Do you know how can a noobaa account/OBC have write-access to multiple buckets? Thank you.

Best regards

**Comment by nimrod-becker** [comment]
The OBC model create a new set of credentials (key/secret) to each. new OBC.
From the NooBaa point of view, it means a new account.

If we want a certain account to have access to multiple buckets, an S3 BucketPolicy can be set on the additional bucket to allow the desired operation for the given account

**Reply by schwienbier** [reply]
Hi @nimrod-becker , thank you very much for your answer. 

First, when you say "S3 BucketPolicy can be set on the additional bucket", do you mean setting namespace policy on bucket class? e.g.

```
apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  name: bc
  namespace: noobaa
spec:
  namespacePolicy:
    type: Multi
    multi:
      writeResource: ns2
      readResources:
      - ns1
```

Or can you please kindly provide me a doucment regarding "S3 BucketPolicy can be set on the additional bucket"? Thank you.

Second, since "allowed_buckets" are removed from noobaa-account-crd since v5.12, how can we assign bucket access to the given account in v5.13?

Best regards
