### ISSUE TITLE
Is there a way to disable public IP and LB type of service?

### ISSUE THREAD

**Issue by mar-ada** [noobaa/noobaa-operator#1012]
I am using ocp 4.8 in an enterprise org and we rely on noobaa. We use the version 5.9.0 available in this openshift version. It seems however that noobaa-management and s3 services are always created as loadBalancer services. Is there anyway to force cluster IP service? These LBs always try to create public IPs and thats not allowed in this private cluster.

**Comment by dpineda64** [comment]
I had the same issue  adding `disableLoadBalancerService: true` to the noobaa system spec  (on k8s) changed the services from LB to ClusterIP and no public ips

**Comment by liranmauda** [comment]
Hi @mar-ada Thanks for reaching out 🙂 
as @dpineda64 said you can use the `disableLoadBalancerService` flag
https://github.com/noobaa/noobaa-operator/blob/356884843f561c62316b6997b66a4be5c47525c9/deploy/crds/noobaa.io_noobaas_crd.yaml#L1221-L1225

you can do it by running: `kubectl edit noobaa noobaa`
and then
```
      memory: 500M
    requests:
      cpu: 100m
      memory: 500M
  dbType: postgres
  disableLoadBalancerService: true         <--------------- Add this 
  endpoints:
    maxCount: 1
    minCount: 1
```

Please pay attention that this flag is introduced in 5.10 and you are using 5.9.0

Let me know If you have any more questions, I will leave this issue open for a while and close it after.
