### ISSUE TITLE
Affinity Not Added to Backingstore Pod after Editing Noobaa CR

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-operator#1066]
### Environment info
NooBaa Operator Version: 5.13.0
Platform: Kubernetes 1.20.2 | minikube 1.18.1

### Actual behavior
1. Affinity does not pass to backingstore pod.

### Expected behavior
1. Affinity will pass to backingstore pod (it will be terminated before).

### Steps to reproduce
Test on minikube
1. Add affinity on the node: `kubectl label nodes minikube name=app-shira` (I chose `name=app-shira` as a new label).
2. If you want to check that your label was added: `kubectl describe nodes minikube`.
3. Change Noobaa CR and add Affinity to it:  `kubectl edit noobaa noobaa`.
4. Paste this inside :
```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: name
            operator: In
            values:
            - app-shira
```
It looks like this (after paste):
<img width="441" alt="Screenshot 2023-02-28 at 12 49 07" src="https://user-images.githubusercontent.com/57721533/221832634-e6426109-1323-4607-b918-40eec8ba2039.png">
5. See the changes of the pods:  `kubectl get pods -w`.
would expect to see the pods core, db, endpoint and backingstore terminated.
