### ISSUE TITLE
Missing docs with examples of all different ways of creating bucket classes.

### ISSUE THREAD

**Issue by bipuladh** [noobaa/noobaa-operator#107]
We need to update the docs to show how different tiering combinations can be used. And explain the structure of the YAML to be used. https://github.com/noobaa/noobaa-operator/blob/master/doc/bucket-class-crd.md

**Comment by guymguym** [comment]
Few examples from @bipuladh :
```
# ex1 - single tier with single BS
spec:
  placementPolicy:
    tiers:
    - backingStores: ["bs1"]

# ex2 - two tiers each with single BS
spec:
  placementPolicy:
    tiers:
    - backingStores: ["bs1"]
    - backingStores: ["bs2"]

# ex3 - one tier with Mirror on two BS
spec:
  placementPolicy:
    tiers:
    - placement: Mirror
      backingStores: ["bs1", "bs2"]

# ex4 - two tiers, first with Mirror, and second with Spread
spec:
  placementPolicy:
    tiers:
    - placement: Mirror
      backingStores: ["bs1", "bs2"]
    - placement: Spread
      backingStores: ["bs3", "bs4", "bs5"]
```
