### ISSUE TITLE
NamespaceStore stucks in Connecting Phase after the pods of noobaa-core and noobaa-endpoint are restarted

### ISSUE THREAD

**Issue by schwienbier** [noobaa/noobaa-operator#1197]
Dear Noobaa Supports,

we are using Noobaa v5.13.0 on k8s v1.25. Currently our noobaa has 200+ NamespaceStores, bucket classes, and OBCs. Some buckets could be in use when we increased the resource limit of noobaa-core and endpoint. Then after the restart of noobaa-core and endpoint, some namespace stores' phases turn into Connecting from Ready. 

The error messages is as follows,

```
RPC: connection (0xc0005fb740) already closed &{RPC:0xc00033a2d0
        Address:wss://noobaa-mgmt.noobaa.svc.cluster.local:443/rpc/ State:closed
        WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0}
        ReconnectDelay:3s cancelPings:<nil>}
```

The complete status in that NamespaceStore is as follows.

```
apiVersion: noobaa.io/v1alpha1
kind: NamespaceStore
metadata:
  ...
  namespace: noobaa
status:
  conditions:
    - lastHeartbeatTime: '2023-08-11T09:07:39Z'
      lastTransitionTime: '2023-08-11T09:07:39Z'
      message: >-
        RPC: connection (0xc0005fb740) already closed &{RPC:0xc00033a2d0
        Address:wss://noobaa-mgmt.noobaa.svc.cluster.local:443/rpc/ State:closed
        WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0}
        ReconnectDelay:3s cancelPings:<nil>}
      reason: TemporaryError
      status: 'False'
      type: Available
    - lastHeartbeatTime: '2023-08-11T09:07:39Z'
      lastTransitionTime: '2023-08-11T09:07:39Z'
      message: >-
        RPC: connection (0xc0005fb740) already closed &{RPC:0xc00033a2d0
        Address:wss://noobaa-mgmt.noobaa.svc.cluster.local:443/rpc/ State:closed
        WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0}
        ReconnectDelay:3s cancelPings:<nil>}
      reason: TemporaryError
      status: 'True'
      type: Progressing
    - lastHeartbeatTime: '2023-08-11T09:07:39Z'
      lastTransitionTime: '2023-08-02T03:52:35Z'
      message: >-
        RPC: connection (0xc0005fb740) already closed &{RPC:0xc00033a2d0
        Address:wss://noobaa-mgmt.noobaa.svc.cluster.local:443/rpc/ State:closed
        WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0}
        ReconnectDelay:3s cancelPings:<nil>}
      reason: TemporaryError
      status: 'False'
      type: Degraded
    - lastHeartbeatTime: '2023-08-11T09:07:39Z'
      lastTransitionTime: '2023-08-11T09:07:39Z'
      message: >-
        RPC: connection (0xc0005fb740) already closed &{RPC:0xc00033a2d0
        Address:wss://noobaa-mgmt.noobaa.svc.cluster.local:443/rpc/ State:closed
        WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0}
        ReconnectDelay:3s cancelPings:<nil>}
      reason: TemporaryError
      status: 'False'
      type: Upgradeable
  mode:
    modeCode: OPTIMAL
    timeStamp: 2023-08-02 03:52:39.487242521 +0000 UTC m=+268.820862603
  phase: Connecting
spec:
  s3Compatible:
    endpoint: ...
    secret:
      name: ...
      namespace: noobaa
    signatureVersion: v4
    targetBucket: ...
  type: s3-compatible

```

Do you know how to recover those namespace stores' phases back to Ready? Thank you.

Best regards
