### ISSUE TITLE
Best Practice to improve the Noobaa Performance of downloading files with size less than 100 MB

### ISSUE THREAD

**Issue by schwienbier** [noobaa/noobaa-operator#1226]
Dear Noobaa Support,

### Environment info
- NooBaa Operator Version: 5.13.0
- Platform: **Kubernetes v1.25.8**

The noobaa is configured as follows in our k8s cluster. It is deployed on 6 tainted k8s nodes with 16 cpus and 128 GB memory. When downloading small files, whose size is less than 100MB, e.g. 20MB, noobaa takes 0.23s, minio takes 0.29s, and swift object storage takes 0.14s.

May I ask, what is the best practice to improve the noobaa's performance of downloading files, especially for files whose size is less than 100 MB, except the approach of increasing the number of endpoints, and resource limits? Thank you.

```
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  labels:
    app: noobaa
  name: noobaa
  namespace: noobaa
spec:
  cleanupPolicy: {}
  coreResources:
    limits:
      cpu: '10'
      memory: 80Gi
    requests:
      cpu: '1'
      memory: 2Gi
  dbImage: public.int.repositories.cloud.sap/centos/postgresql-12-centos7
  dbResources:
    limits:
      cpu: '4'
      memory: 8Gi
    requests:
      cpu: '4'
      memory: 8Gi
  dbType: postgres
  disableLoadBalancerService: true
  endpoints:
    maxCount: 8
    minCount: 8
    resources:
      limits:
        cpu: '3'
        memory: 5Gi
      requests:
        cpu: '1'
        memory: 2Gi
  image: public.int.repositories.cloud.sap/noobaa/noobaa-core:master-20230123
  loadBalancerSourceSubnets: {}
  security:
    kms: {}
```

Best regards
