### ISSUE TITLE
bucketclass set in yaml file doesn't take effect while create obc using kubectl create 

### ISSUE THREAD

**Issue by lzw06061139** [noobaa/noobaa-operator#1500]
### Environment info
- NooBaa Operator Version: 5.17.1
- Platform:  minikube 1.34.0

### Actual behavior
1. create obc with yaml, bucketclass set in yaml file doesn't take effect. the result of "noobaa obc list" shows that the default bucket class "noobaa-default-bucket-class" is set.
% sudo noobaa obc list 
NAMESPACE   NAME                  BUCKET-NAME       STORAGE-CLASS      BUCKET-CLASS                  PHASE   
noobaa      llm-multi-store-obc   llm-multi-store   noobaa.noobaa.io   **noobaa-default-bucket-class**   Bound

But, "kubectl describe -n noobaa objectbucketclaim llm-multi-store-obc" shows the bucketclass set success.
Name:         llm-multi-store-obc
Namespace:    noobaa
Labels:       app=noobaa
              bucket-provisioner=noobaa.noobaa.io-obc
              noobaa-domain=noobaa.noobaa.io
Annotations:  <none>
API Version:  objectbucket.io/v1alpha1
Kind:         ObjectBucketClaim
Metadata:
  Creation Timestamp:  2025-01-03T06:33:29Z
  Finalizers:
    objectbucket.io/finalizer
  Generation:        2
  Resource Version:  782679
  UID:               4e512325-01be-4ca8-87e8-f1913a3c5757
Spec:
  Additional Config:
    Bucketclass:         **llm-multi-bucket-class**
  Bucket Name:           llm-multi-store
  Generate Bucket Name:  llm-multi-store
  Object Bucket Name:    obc-noobaa-llm-multi-store-obc
  Storage Class Name:    noobaa.noobaa.io
Status:
  Phase:  Bound
Events:   <none>

### Expected behavior
1. the bucketclass set in yaml files takes effect

### Steps to reproduce
1. create two namespace stores
% sudo noobaa namespacestore create s3-compatible llm-store2-ns --endpoint={endpoint} --target-bucket=llm-store2 --signature-version=v2
% sudo noobaa namespacestore create s3-compatible llm-store-ns --endpoint={endpoint} --target-bucket=llm-store --signature-version=v2
2. create a "multi" type bucket class
% sudo noobaa bucketclass create namespace-bucketclass multi llm-multi-bucket-class --write-resource=llm-store2-ns --read-resources=llm-store-ns
3. create obc with yaml
```
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: llm-multi-store-obc
  namespace: noobaa
spec:
  additionalConfig:
    Bucketclass: llm-multi-bucket-class
  generateBucketName: llm-multi-store
  bucketName: llm-multi-store
  storageClassName: noobaa.noobaa.io
```
% sudo kubectl create -f obc.yaml
### More information - Screenshots / Logs / Other output
![image](https://github.com/user-attachments/assets/23461f65-8043-4084-a769-50c2104eea60)
