### ISSUE TITLE
Feature request/low hanging fruit: Allow changing the MongoDB URL via the NooBaa CR

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-operator#304]
Since noobaa-db and noobaa-core are now separated it would make sense to have the possibility to redirect the MongoDB transactions to a external MongoDB instance.

Currently the operator sets the environment variable MONGODB_URL according to the name of the corresponding NooBaa CR. If the NooBaa CRD would be extended by a field where you can set this environment variable to a custom URL it would easily be possible to use an external MongoDB instance.
Also when this field is set to a custom MongoDB URL it would be possible to not deploy the noobaa-db statefulset and force noobaa-core to initialize the external MongoDB , if it is empty.

At the moment it is not possible to change MONGODB_URL manually via kubectl/oc set env because the operator immediately resets it.

**Comment by guymguym** [comment]
Hi @lallinger-arbeit 
That's a great suggestion and I also agree it makes sense.
Can you describe some more of why/when you prefer to use an external DB? 
It would be very useful for us to understand more on this use-case and which solutions would benefit from it.
Thanks!

**Comment by lallinger-arbeit** [comment]
Hi @guymguym 
In a develop environment, where it does not matter if any data is lost, the current deployment of the noobaa-db via statefulset is sufficient.

But in a production environment this can lead to problems. For example when all workload from cluster is moved to another cluster it is not easily possible to backup and restore PVCs without any downtime. Because of this we would like that noobaa uses a MongoDB which is outside of the cluster and under our full control, so we can also easily create backups of the MongoDB.

Currently we are already using an external MongoDB for noobaa. For this we use a script to override the MONGODB_URL env inside the noobaa-core and noobaa-endpoint pods. This is working fine, but it is a quite ugly hack.

Also it would be good if the connection between noobaa-core/noobaa-endpoint and the MongoDB would use a username and password for added security.

I think every solution which wants to move noobaa from one cluster to an other without downtime and data loss would benefit from this. Also the MongoDB can then be shared with other applications which would result in better usage of resources.

**Comment by lallinger-arbeit** [comment]
We now pointed NoooBaa to a remote MongoDB replicaset. For this we used the already existing environment variable MONGO_RS_URL of noobaa-core/endpoint.
Setting this environment variable and the configuration for the used CA and cert (/data/mongo/ssl/) manually works fine. There is only one major downside: 
You need to prevent noobaa-core to initialize the noobaa-db pod which automatically gets deployed when installing via the cli. This can be done by providing an invalid storage class to the cli and then patching the above described settings manually in the noobaa-core statefulset. After this the core pod can initialize the remote MongoDB and create the noobaa-endpoint deployment, which then needs to be patched manually again...

It would really be nice if it would be possible to set at least one of MONGODB_URL or MONGO_RS_URL (or at best both) using the NooBaa CR!

**Comment by liranmauda** [comment]
@lallinger-arbeit 
I have created a PR for changing the MONGODB_URL, can you check it?

Regarding MONGO_RS_URL we want to remove this path: https://github.com/noobaa/noobaa-core/issues/6127

**Comment by lallinger-arbeit** [comment]
@liranmauda sorry for the late response, i've been on vacation the last two weeks.. i'll try to test it this week!

**Comment by lallinger-arbeit** [comment]
@liranmauda I just tried your pull request and noticed a few things.

First off you check if the given MongoDB URL contains `mongodb://` and raise an error if it doesn't. You should also check for the seedlist format, which is `mongodb+srv://` [see here](https://docs.mongodb.com/manual/reference/connection-string/#connections-dns-seedlist)

The MongoDB URL also can contain credentials in the form of `mongodb://user:password@mongoserver.com/...` which are sensitive informations. We also use ArgoCD to rollout the NooBaa CR to the cluster, hence we would need to check in the credentials unencrypted to our git repository. It would be really nice if it was possible to load the `mongoDbURL` from an kubernetes secret. I'm thinking of something like this, for the case where you directly specify the URL:
```
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  labels:
    app: noobaa
  name: noobaa
spec:
  mongoDbURL:
    value: "mongodb://no-auth-mongo-server.com/nbcore"
```

And for the case where you store the URL in a secret:
```
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  labels:
    app: noobaa
  name: noobaa
spec:
  mongoDbURL:
    valueFrom:
      secretKeyRef:
        name: secret-name
        key: mongodb-url
```

And after building the current master of noobaa-operator with your changes i noticed, that the image name for the default backingstore is not set correctly. It currently gets set to `NOOBAA_CORE_IMAGE` when specifying a custom noobaa-core image (i did not test the behaviour without specifying a custom image). But this is probably not connected to your pull request.

But thank you very much for looking into this!

**Comment by lallinger-arbeit** [comment]
The problem with `NOOBAA_CORE_IMAGE` may be related to your pull request. When not specifying `mongoDbURL` the default backing store is working as intended.

Here are the two different NooBaa CRs:
```
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  labels:
    app: noobaa
  name: noobaa
  namespace: noobaa-one
spec:
  endpoints:
    maxCount: 10
    minCount: 1
  image: 'custom/built/image'
  mongoDbURL: >-
    mongodb://noobaa:password@bdp-mongodb-q.rsint.net/nbcore?authSource=nbcore&ssl=true&tlsAllowInvalidCertificates=true
```
This one leads to the following default backingstore pod being deployed:
```
kind: Pod
apiVersion: v1
metadata:
  name: noobaa-default-backing-store-noobaa-pod-3e3108d7
  namespace: noobaa-one
  labels:
    app: noobaa
spec:
...
  containers:
    - image: NOOBAA_CORE_IMAGE
...
```

Using this CR the default backing store starts as inteded:
```
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  labels:
    app: noobaa
  name: noobaa
spec:
  dbStorageClass: block
  dbType: mongodb
  endpoints:
    maxCount: 10
    minCount: 1
  image:  'custom/built/image'
```
