### ISSUE TITLE
Helmization of noobaa operator

### ISSUE THREAD

**Issue by yaroslavkasatikov** [noobaa/noobaa-operator#305]
Hello team,

Faced to several issue while was trying to create helm chart for creating resources.
I have attached yaml files which were generated by Helm.

list of issues:
1) If I created all resources ( noobaa, backingstores, bucketclasses, storage classes and obc) simultaneously, I see that all my backingstores are rejected because there is no 'noobaa' object created yet and this resources leave it this status despite noobaa is already created. It blocks everything to continue.  

2) Backingstores removal. I delete helm chart with all resources (except noobaa, because I moved it out from the chart according to reason from #1. All obc, sc and bucketclasses are remove, but Backingstores stuck:
```Status:
  Conditions:
    Last Heartbeat Time:   2020-05-15T13:44:23Z
    Last Transition Time:  2020-05-15T14:10:44Z
    Message:               DeletePoolAPI cannot complete because pool "pvc-pool-2" has buckets attached
    Reason:                ResourceInUse
    Status:                Unknown
    Type:                  Available
    Last Heartbeat Time:   2020-05-15T13:44:23Z
    Last Transition Time:  2020-05-15T14:10:44Z
    Message:               DeletePoolAPI cannot complete because pool "pvc-pool-2" has buckets attached
    Reason:                ResourceInUse
    Status:                False
    Type:                  Progressing
    Last Heartbeat Time:   2020-05-15T13:44:23Z
    Last Transition Time:  2020-05-15T14:10:44Z
    Message:               DeletePoolAPI cannot complete because pool "pvc-pool-2" has buckets attached
    Reason:                ResourceInUse
    Status:                True
    Type:                  Degraded
    Last Heartbeat Time:   2020-05-15T13:44:23Z
    Last Transition Time:  2020-05-15T14:10:44Z
    Message:               DeletePoolAPI cannot complete because pool "pvc-pool-2" has buckets attached
    Reason:                ResourceInUse
    Status:                Unknown
    Type:                  Upgradeable
```

So there are no obc:

[yaroslav@yaroslav noobaa-resources]$ oc get obc

No resources found.
But buckets are still exist in UI (see screenshoft 'bucket.png')
So it blocks correct removal.

3) it's not related to helm, but I got the issue with csv:

```
[yaroslav@yaroslav noobaa-resources]$ oc get csv
NAME                                   DISPLAY                        VERSION   REPLACES                               PHASE
lib-bucket-provisioner.v1.0.0          lib-bucket-provisioner         1.0.0                                            Failed
noobaa-operator.v2.1.0                 NooBaa Operator                2.1.0     noobaa-operator.v2.0.10                Succeeded
openshift-pipelines-operator.v0.11.2   OpenShift Pipelines Operator   0.11.2    openshift-pipelines-operator.v0.10.7   Succeeded

```

Status:

```
  Version:  1.0.0
Status:
  Certs Last Updated:  <nil>
  Certs Rotate At:     <nil>
  Conditions:
    Last Transition Time:  2020-05-14T14:57:16Z
    Last Update Time:      2020-05-14T14:57:16Z
    Message:               OwnNamespace InstallModeType not supported, cannot configure to watch own namespace
    Phase:                 Failed
    Reason:                UnsupportedOperatorGroup
  Last Transition Time:    2020-05-14T14:57:16Z
  Last Update Time:        2020-05-14T14:57:16Z
  Message:                 OwnNamespace InstallModeType not supported, cannot configure to watch own namespace
  Phase:                   Failed
  Reason:                  UnsupportedOperatorGroup
```

I installed with this subscription yaml:

```
apiVersion: v1
kind: Namespace
metadata:
  name: noobaa
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: noobaa
spec:
  targetNamespaces:
  - noobaa
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: noobaa
  namespace: noobaa
spec:
  channel: alpha
  name: noobaa-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
```

So, please feel free to ask any question or additional details.

Yaml which has been generated by Helm:

```
# Source: noobaa/templates/noobaa-operator.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: noobaa
  namespace: noobaa
spec:
  channel: alpha
  name: noobaa-operator
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace
---
# Source: noobaa/templates/noobaa-sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: noobaa-pvc-pool-1.noobaa.io
provisioner: noobaa.noobaa.io/obc
reclaimPolicy: Delete
parameters:
  bucketclass: pvc-pool-1
---
# Source: noobaa/templates/noobaa-sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: noobaa-pvc-pool-2.noobaa.io
provisioner: noobaa.noobaa.io/obc
reclaimPolicy: Delete
parameters:
  bucketclass: pvc-pool-2
---
# Source: noobaa/templates/noobaa-resource.yaml
#apiVersion: noobaa.io/v1alpha1
#kind: NooBaa
#metadata:
#  labels:
#    app: noobaa
#  name: noobaa
#  namespace: noobaa
#
#spec:
#  dbResources:
#    requests:
#      cpu: "1"
#      memory: 1Gi
---
# Source: noobaa/templates/pvpool.yaml
apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  finalizers:
  - noobaa.io/finalizer
  labels:
    app: noobaa
  name: pvc-pool-1
  namespace: noobaa
spec:
  pvPool:
    numVolumes: 3
    resources:
      requests:
        storage: 30G
    storageClass: gp2
  type: pv-pool
---
# Source: noobaa/templates/pvpool.yaml
apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  finalizers:
  - noobaa.io/finalizer
  labels:
    app: noobaa
  name: pvc-pool-2
  namespace: noobaa
spec:
  pvPool:
    numVolumes: 3
    resources:
      requests:
        storage: 30G
    storageClass: gp2
  type: pv-pool
---
# Source: noobaa/templates/bucketclass.yaml
apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  labels:
    app: noobaa
  name: pvc-pool-1
  namespace: noobaa
spec:
  placementPolicy:
    tiers:
    - backingStores:
      - pvc-pool-1
---
# Source: noobaa/templates/bucketclass.yaml
apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  labels:
    app: noobaa
  name: pvc-pool-2
  namespace: noobaa
spec:
  placementPolicy:
    tiers:
    - backingStores:
      - pvc-pool-2
---
# Source: noobaa/templates/obc-pool.yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: bucket1
  namespace: noobaa
spec:
  generateBucketName: bucket1
  storageClassName: noobaa-pvc-pool-1.noobaa.io
---
# Source: noobaa/templates/obc-pool.yaml
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: bucket2
  namespace: noobaa
spec:
  generateBucketName: bucket2
  storageClassName: noobaa-pvc-pool-2.noobaa.io
```
