### ISSUE TITLE
CLI Command - noobaa perf test (enhancement)

### ISSUE THREAD

**Issue by guymguym** [noobaa/noobaa-operator#310]
I was thinking to start adding performance related functionality using the CLI and this is the first idea. My intention with `noobaa perf test` is to run a quick performance benchmark, that by default takes no more than 1 minute, and print simple simple simple performance stats. 

I want it to support running either from the CLI host itself, or in-cluster by creating an in-cluster kubernetes job that will run the same benchmark but from within the cluster network.

I think the output should be as simple as this:
(at least by default, we can always introduce more verbosity with flags)
```
Streaming:
  GET: 350 MB/sec
  PUT: 360 MB/sec

Latency:
  GET: 10 ms
  PUT: 20 ms

IOPS:
  GET: 1000 op/sec
  PUT: 1000 op/sec
```

@noobaa/dev @shekharberry
