### ISSUE TITLE
Unable to create S3 backing store

### ISSUE THREAD

**Issue by pranavgaikwad** [noobaa/noobaa-operator#42]
**Issue :**

When trying to create a S3 `BackingStore`, it results in being `Rejected`.

```
NAME           TYPE      BUCKET-NAME  PHASE      AGE
bstore-s3-00   aws-s3    <bucket>            Rejected   1h
``` 

BackingStore defn :
```
apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  name: bstore-s3-00
  labels:
    app: noobaa
    type: aws-s3
  finalizers:
    - noobaa.io/finalizer
spec:
  type: aws-s3
  s3Options:
    endpoint: s3.amazonaws.com
  bucketName: <bucket_name>
  secret:
    name: aws-s3-00
    namespace: noobaa
```

S3 secret : 
```
apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: <ID>
  AWS_SECRET_ACCESS_KEY: <KEY>
kind: Secret
metadata:
  labels:
    app: noobaa
  name: aws-s3-00
  namespace: noobaa
type: Opaque
```

Operator Logs : 
```
time="2019-08-28T14:20:50Z" level=info msg="Start ..." backingstore=noobaa/bstore-s3-00
time="2019-08-28T14:20:50Z" level=info msg="✅ Exists: BackingStore \"bstore-s3-00\"\n"
time="2019-08-28T14:20:50Z" level=info msg="✅ Exists: NooBaa \"noobaa\"\n"
time="2019-08-28T14:20:50Z" level=info msg="✅ Exists: Secret \"aws-s3-00\"\n"
time="2019-08-28T14:20:50Z" level=info msg="SetPhase: Verifying" backingstore=noobaa/bstore-s3-00
time="2019-08-28T14:20:50Z" level=info msg="SetPhase: Connecting" backingstore=noobaa/bstore-s3-00
time="2019-08-28T14:20:50Z" level=info msg="✅ Exists: NooBaa \"noobaa\"\n"
time="2019-08-28T14:20:50Z" level=info msg="✅ Exists: Service \"noobaa-mgmt\"\n"
time="2019-08-28T14:20:50Z" level=info msg="✅ Exists: Secret \"noobaa-operator\"\n"
time="2019-08-28T14:20:50Z" level=info msg="✈️  RPC: system.read_system() Request: <nil>"
time="2019-08-28T14:20:50Z" level=info msg="✅ RPC: system.read_system() Response OK: &{Op:res RequestID:1@https://::ffff:10.129.2.1:43396(1hqoo0ilep) Took:8.719151020050049 Error:<nil>}"
time="2019-08-28T14:20:50Z" level=info msg="SetPhase: Creating" backingstore=noobaa/bstore-s3-00
time="2019-08-28T14:20:50Z" level=info msg="✈️  RPC: account.check_external_connection() Request: {Name:bstore-s3-00 EndpointType:AWS Endpoint:s3.amazonaws.com Identity:<MY_IDENTITY> Secret:<MY_SECRET> AuthMethod:}"
time="2019-08-28T14:20:50Z" level=info msg="✅ RPC: account.check_external_connection() Response OK: &{Op:res RequestID:1@https://::ffff:10.129.2.1:43396(1hqoo6y6dq) Took:246.1275309920311 Error:<nil>}"
time="2019-08-28T14:20:50Z" level=info msg="SetPhase: Rejected" backingstore=noobaa/bstore-s3-00
time="2019-08-28T14:20:50Z" level=error msg="❌ Persistent Error: BackingStore \"bstore-s3-00\" invalid external connection \"INVALID_ENDPOINT\""" backingstore=noobaa/bstore-s3-00
```

**More Info :**
I tried debugging the RPC connection bit. Here's the error message received from AWS :
```
 "Invalid character in header content ["Authorization"]
```

**Version**
- OpenShift 4.1.0
- NooBaa Operator v1.1.0 (non OLM)
