### ISSUE TITLE
Unable to migrate from MongoDB to Postgres in disconnected environments - ImagePullBackOff/ErrImagePull

### ISSUE THREAD

**Issue by snorwin** [noobaa/noobaa-operator#822]
### Environment info
- NooBaa Version:  noobaa/noobaa-core:master-20211205
- Platform: **Kubernetes v1.21.1+6438632 | OpenShift 4.8.17**

### Actual behavior
If for both databases (i.e. MongoDB and Postgres) a custom image must be used, because the cluster is running in a disconnected environment, either the `noobaa-db-0`  or the `noobaa-db-pg-0` pod ends up in a ImagePullBackOff/ErrImagePull error state because only one DB image can be customized at the same time.

### Expected behavior
Both database images can be customized independently from each other in order to facilitate migration from MongoDB to Postgres in disconnected environments. 

OR

The operator doesn't update the  existing `noobaa-db` SS while migrating the database from MongoDB to Postgres.

### Steps to reproduce
1. Create a NooBaa CR using a custom image, ensure that you are unable to pull the default image.
```
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: noobaa
  namespace: noobaa-operator
spec:
  dbType: mongodb
  dbImage: 'xxxxx/mongo:3.6.23-rh'
```

2. Update the `dbType` and `dbImage`:
```
apiVersion: noobaa.io/v1alpha1
kind: NooBaa
metadata:
  name: noobaa
  namespace: noobaa-operator
spec:
  dbType: postgres
  dbImage: 'xxxxx/rhel8/postgresql-12:1'
```
